title: Glasgow Improv Theatre - The GIT
email: glasgowimprovtheatre@gmail.com
description: "Glasgow Improv Theatre - The GIT. Improv classes, workshops, and shows in Glasgow, Scotland."

plugins:
  - jekyll-redirect-from

baseurl: "" # the subpath of your site, e.g. /blog
url: http://improvglasgow.co.uk # the base hostname & protocol for your site, e.g. http://example.com

showImageCount: 354

mailing-list-link: https://improvglasgow.co.uk/mailing-list
review-link-google: https://g.page/r/CeXEfSfYqbhhEBM/review
review-link-tripadvisor: https://www.tripadvisor.co.uk/UserReviewEdit-g186534-d18856895-Glasgow_Improv_Theatre-Glasgow_Scotland.html

social:
  - title: instagram
    url: http://instagram.com/improvglasgow
  - title: facebook
    url: http://facebook.com/improvglasgow
  - title: twitter
    url: http://twitter.com/improvglasgow
  - title: youtube
    url: https://www.youtube.com/@ImprovGlasgow
  - title: tiktok
    url: https://www.tiktok.com/@improvglasgow
#  - title: twitch
#    url: http://twitch.tv/improvglasgow

teachers:
  - name: Martin
    headshot: martin1.jpg
    email: glasgowimprovtheatre@gmail.com
    description: |
      Martin James founded the Glasgow Improv Theatre and studied improv at the Upright Citizen Brigade Theatre in Los Angeles. He hosts and performs in Campfire Improv, a monthly show at Monkey Barrel Comedy in Edinburgh. At the Glasgow Improv Theatre, he wears many hats—teaching classes, hosting shows, performing regularly, and handling tech and behind-the-scenes admin. He has performed at festivals across the UK and internationally, including the Edinburgh Fringe, Glasgow Comedy Festival, Del Close Marathon in New York, and festivals in Los Angeles, Reykjavík, London, Bristol, Leeds, and Newcastle. Martin launched Glasgow Harold Night in 2016, which has run every month since, pausing only for global pandemics.

  - name: John
    headshot: john2.jpg
    email: glasgowimprovtheatre@gmail.com
    description: |
      John McInnes has been doing longform improv since 2014 and loves it, particularly "The Harold". He's studied improv at the Upright Citizens Brigade Theatre and has learned from Carleen MacDermid, Will Hines, Billy Merritt, Julie Brister... and many more. In 2016 he co-founded Bristol's Kitchen Rules Theatre and was a member of every cool improv team in Bristol from 2016-2023. He is now a member of Couch and co-runs Improv Cage Match at the Edinburgh Fringe. He has performed at the Del Close Marathon, Amsterdam Improv Marathon, Hoopla Improv Marathon and the Robin Hood International Improv Festival (not a marathon).

  - name: Jeff
    headshot: jeff1.jpg
    email: jeffkgit@gmail.com
    description: |
      Jeff Khan has a decade of improv experience. He trained at the Free Association in London, as well as with improvisers from the Upright Citizens Brigade. Jeff is a founding member of the Glasgow Improv Theatre's long-running house team, Couch. He was also a member of the Free Association's house team Minority Report. He regularly performs at the Edinburgh Fringe and comedy festivals.


  - name: Karen
    headshot: karen1.jpg
    email: KarenDGIT@gmail.com
    description: |
      Karen Davidson has been a fixture in the Glasgow improv scene since 2019. Having trained with the Glasgow Improv Theatre, the Upright Citizens Brigade and the World’s Greatest Improv School she has been taught and inspired by some of the best improv teachers around. She has appeared in the legendary podcast Improv4Humans, with Matt Besser of UCB, and has performed in events such as Edinburgh Fringe, Glasgow International Comedy Festival, Edinburgh International Improv Festival, Robin Hood Improv Festival and others.

teams:
  - name: Couch
    icon: fa-couch
    description: |
      <p>
          Couch are a long-form improv team from Glasgow. They were the first Glasgow Improv Theatre house team for Glasgow Harold Night. They have also been seen at Improv F*cktown, and Improv Cage Match.
      </p>
      <p>
          Their members have trained at the Upright Citizens Brigade Theatre, and have performed at festivals such as DCM in New York and the Edinburgh Fringe Festival. 
      </p>
      <p>
          Couch Surfs The Web: A night of improv comedy where Couch looks up bad reviews of places you've been to!
      </p>
    socials:
      - title: twitter
        url: http://twitter.com/couchimprov

      - title: facebook
        url: http://facebook.com/couchimprov

      - title: instagram
        url: http://instagram.com/couchimprov

  - name: Bounce House
    icon: fa-chess-rook
    description: |
      <p>
          GIT House team
      </p>
      <p>
        Bounce House are on a mission - to solve all of the petty squabbles they come across.
      </p>
      <p>
        Whether it's a random Am I The Asshole post on Reddit or a conundrum shared by an audience member they're here to help. Armed only with bold confidence and longform improv, come along and laugh as Bounce House fix the weird and wonderful issues we all face. You'll leave feeling 10x better*
      </p>
      <p>
        *Bounce House guidance does not constitute medical, legal or useful advice.
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/bouncehouseimprov

  - name: Spread
    icon: fa-newspaper
    description: |
      <p>
          GIT House team
      </p>
      <p>
        Spread presents: Under the Covers.
      </p>
      <p>
        Improvised comedy inspired by print media!
      </p>
      <p>
        Spread will delve under the covers of the weird and wonderful world of gossip magazines to find inspiration for their comedy scenes.
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/spreadimprov

  - name: Saved by the Beep
    icon: fa-bell
    description: |
      <p>
          GIT Harold team
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/savedbythebeep.improv

  - name: With Bits!
    icon: fa-glass-water
    description: |
      <p>
          GIT Harold team
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/withbits.improv

  - name: tubducky
    icon: fa-bath
    description: |
      <p>
          GIT Hamish team
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/tubducky.improv

  - name: Smoking Cat
    icon: fa-cat
    description: |
      <p>
          GIT Hamish team
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/smokingcat.improv

former-teams:

  - name: F.L.U.S.H.
    icon: fa-water
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2024/2025)
      </p>
      <p>
        What on Earth does F.L.U.S.H. mean... Is it a beautiful poker hand? An unimaginable amount of money? Toilet thing? Come to GIT Harold night to find out!*
      </p>
      <p>
        *We cannot guarantee closure on this. 
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/flushprov

  - name: Raintown
    icon: fa-cloud-rain
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2024/2025)
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/raintownimprov


  - name: Yer Da
    icon: fa-users
    description: |
      <p>
          The test to determine who Yer Da is came back inconclusive, but this bunch of improvisers will perform for your acceptance anyway.
      </p>
      <p>
          Team members have been spotted doing guest appearances on legendary podcast Improv4Humans.
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/yerdaimprov

  - name: Family Dinner
    icon: fa-utensils
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2023/2024)
      </p>
      <p>
          Welcome to Family Dinner: Serving up some seriously funny improv and good clean fun that the whole family can enjoy
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/familydinner_improv

  - name: Ghost Fish
    icon: fa-ghost
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2023/2024)
      </p>
      <p>
          One of the all-time great improv groups - hugely influential in the sea, and the standard-bearers for how good, funny and artful long-form improv could be. At their best, they could play manic silliness and slow, patient moments in the same show. They're all dead humans who are now human-looking ghost fish.
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/ghostfishimprov

  - name: One Big Jacket
    icon: fa-tshirt
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2022/2023)
      </p>
      <p>
          One Big Jacket are warm, versatile and entirely waterproof. Made from several sustainably sourced improvisers and held together by the Harold structure.
          <br />** Must not be washed above 40°C
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/onebigjacket.improv

  - name: God's Lettuce
    icon: fa-leaf
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2022/2023)
      </p>
      <p>
          With members from Glasgow to Edinburgh, and even Falkirk, God’s Lettuce provides a diverse range of funny. Cool cats coming at ya large, as the Lettuce intended.
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/gods.lettuce.improv
        
  - name: President Dog
    icon: fa-dog
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2022/2023)
      </p>
      <p>
          President Dog have a legally elected mandate to make you laugh
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/presidentdogimprov

events:
  - event-name: "Hamish Night (Glasgow Comedy Fest)"
    event-date: "2026-03-16"
    event-time: "19:00"
    event-url: "https://www.glasgowcomedyfestival.com/performances/hamish-night-glasgow-improv-theatre/"
    event-image: "https://www.glasgowcomedyfestival.com/wp-content/uploads/2025/11/11-07-2025-135219-4336-768x432.jpg"
    is-sold-out: false
    event-summary: "Two Glasgow Improv Theatre house teams performing The Harold. Featuring tubducky and Smoking Cat!"
    venue-name: "The Old Hairdressers"
    venue-address: "12 Renfield Street, Glasgow, G2 5AR"

  - event-name: "Pretty Thistle (Glasgow Comedy Fest)"
    event-date: "2026-03-16"
    event-time: "20:30"
    event-url: "https://www.glasgowcomedyfestival.com/performances/pretty-thistle-glasgow-improv-theatre/"
    event-image: "https://www.glasgowcomedyfestival.com/wp-content/uploads/2025/11/11-07-2025-141004-8435.jpg"
    is-sold-out: false
    event-summary: "Pretty Thistle is an improv show from Martin James and John McInnes from the Glasgow Improv Theatre. A fully improvised comedy show from an audience suggestion."
    venue-name: "The Old Hairdressers"
    venue-address: "12 Renfield Street, Glasgow, G2 5AR"

  - event-name: "Harold Night (Glasgow Comedy Fest)"
    event-date: "2026-03-17"
    event-time: "19:00"
    event-url: "https://www.glasgowcomedyfestival.com/performances/harold-night-glasgow-improv-theatre/"
    event-image: "https://www.glasgowcomedyfestival.com/wp-content/uploads/2025/11/11-07-2025-135902-7343.jpg"
    is-sold-out: false
    event-summary: "Two Glasgow Improv Theatre house teams performing a fully improvised comedy show. Feat. Saved By The Beep and With Bits!"
    venue-name: "The Old Hairdressers"
    venue-address: "12 Renfield Street, Glasgow, G2 5AR"

  - event-name: "Couch Surfs the Web (Glasgow Comedy Fest)"
    event-date: "2026-03-17"
    event-time: "20:30"
    event-url: "https://www.glasgowcomedyfestival.com/performances/couch-surfs-the-web-glasgow-improv-theatre-2/"
    event-image: "https://www.glasgowcomedyfestival.com/wp-content/uploads/2025/11/11-07-2025-140250-8618.jpg"
    is-sold-out: false
    event-summary: "A night of improv comedy where Couch looks up bad reviews of places you’ve been to!"
    venue-name: "The Old Hairdressers"
    venue-address: "12 Renfield Street, Glasgow, G2 5AR"
    
  - event-name: "Bounce House Solves Everything (Glasgow Comedy Fest)"
    event-date: "2026-03-24"
    event-time: "19:00"
    event-url: "https://www.glasgowcomedyfestival.com/performances/bounce-house-solves-everything-glasgow-improv-theatre/"
    event-image: "https://www.glasgowcomedyfestival.com/wp-content/uploads/2025/11/11-07-2025-140442-6344.jpg"
    is-sold-out: false
    event-summary: "Solving all of the petty squabbles they come across with improv comedy"
    venue-name: "The Old Hairdressers"
    venue-address: "12 Renfield Street, Glasgow, G2 5AR"
    
  - event-name: "Spread Under the Covers"
    event-date: "2026-03-24"
    event-time: "20:30"
    event-url: "https://www.glasgowcomedyfestival.com/performances/spread-under-the-covers-glasgow-improv-theatre/"
    event-image: "https://www.glasgowcomedyfestival.com/wp-content/uploads/2025/11/11-07-2025-140624-7080.jpg"
    is-sold-out: false
    event-summary: "Improvised comedy inspired by print media!"
    venue-name: "The Old Hairdressers"
    venue-address: "12 Renfield Street, Glasgow, G2 5AR"