title: Glasgow Improv Theatre - The GIT
email: glasgowimprovtheatre@gmail.com
description: "Glasgow Improv Theatre - The GIT. Improv classes, workshops, and shows in Glasgow, Scotland."

baseurl: "" # the subpath of your site, e.g. /blog
url: http://improvglasgow.co.uk # the base hostname & protocol for your site, e.g. http://example.com

mailing-list-link: https://dashboard.mailerlite.com/forms/402795/85431937313801728/share

social:
  - title: instagram
    url: http://instagram.com/improvglasgow
  - title: facebook
    url: http://facebook.com/improvglasgow
  - title: twitter
    url: http://twitter.com/improvglasgow
  - title: youtube
    url: https://www.youtube.com/channel/UC7eUy-KQZLZS4rqLz_zQjnQ/
  - title: tiktok
    url: https://www.tiktok.com/@improvglasgow
#  - title: twitch
#    url: http://twitch.tv/improvglasgow

teachers:
  - name: Martin
    headshot: martin1.jpg
    description: |
      Martin James is a founder of the Glasgow Improv Theatre. He studied improv at the Upright Citizens Brigade Theatre in Los Angeles. Martin started Glasgow Harold Night in 2016 where it has run every month pausing only for global pandemics. As part of Couch, Martin is a house team performer in Couch Surfs the Web, Glasgow Harold Night, Improv Fucktown and the Edinburgh Fringe show Improv Cage Match. He also performs with Pretty Thistle, a 2-prov team with John McInnes. He performed two shows at the Del Close Marathon in New York, one wearing an adult diaper (it was improvised The Boss Baby).

  - name: John
    headshot: john2.jpg
    description: |
      John McInnes has been doing longform improv since 2014 and loves it, particularly "The Harold". He's studied improv at the Upright Citizens Brigade Theatre and has learned from Carleen MacDermid, Will Hines, Billy Merritt, Julie Brister... and many more. In 2016 he co-founded Bristol's Kitchen Rules Theatre and was a member of every cool improv team in Bristol from 2016-2023. He is now a member of Couch and co-runs Improv Cage Match at the Edinburgh Fringe. He has performed at the Del Close Marathon, Amsterdam Improv Marathon, Hoopla Improv Marathon and the Robin Hood International Improv Festival (not a marathon).

  - name: Jeff
    headshot: jeff1.jpg
    description: |
      Jeff Khan has a decade of improv experience. He trained at the Free Association in London, as well as with improvisers from the Upright Citizens Brigade. Jeff is a founding member of the Glasgow Improv Theatre's long-running house team, Couch. He was also a member of the Free Association's house team Minority Report. He regularly performs at the Edinburgh Fringe and comedy festivals.


  - name: Karen
    headshot: karen1.jpg
    description: |
      Karen Davidson has been a fixture in the Glasgow improv scene since 2019. Having trained with the Glasgow Improv Theatre, the Upright Citizens Brigade and the World’s Greatest Improv School she has been taught and inspired by some of the best improv teachers around. She has appeared in the legendary podcast Improv4Humans, with Matt Besser of UCB, and has performed in events such as Edinburgh Fringe, Glasgow International Comedy Festival, Edinburgh International Improv Festival, Robin Hood Improv Festival and others. She can be found performing at the Old Hairdressers on the third Tuesday of every month with her team Yer Da.

teams:
  - name: Couch
    icon: fa-couch
    description: |
      <p>
          Couch are a long-form improv team from Glasgow. They were the first Glasgow Improv Theatre house team for Glasgow Harold Night. They have also been seen at Improv F*cktown, and Improv Cage Match.
      </p>
      <p>
          Their members have trained at the Upright Citizens Brigade Theatre, and have performed at festivals such as DCM in New York and the Edinburgh Fringe Festival. 
      </p>
      <p>
          They are going to do a Harold and need a suggestion to get started. Or they are going to do their Improv Spotify show, please add songs to their playlist.
      </p>
    socials:
      - title: twitter
        url: http://twitter.com/couchimprov

      - title: facebook
        url: http://facebook.com/couchimprov

      - title: instagram
        url: http://instagram.com/couchimprov

  - name: Yer Da
    icon: fa-users
    description: |
      <p>
          The test to determine who Yer Da is came back inconclusive, but this bunch of improvisers will perform for your acceptance anyway.
      </p>
      <p>
          You'll find them performing monthly at Glasgow Improv Theatre in their show Yer Da Wants a Word where they do a set (probably a Haroldy montage, it makes sense honest) before hosting arguably the funnest improv jam around.
      </p>
      <p>
          Team members have been spotted doing guest appearances on legendary podcast Improv4Humans, Will Hines' How Was Your Week and in late night Edinburgh improv show Dating Crapp.
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/yerdaimprov
        
  - name: F.L.U.S.H.
    icon: fa-water
    description: |
      <p>
          GIT House team at Glasgow Harold Night
      </p>
      <p>
        What on Earth does F.L.U.S.H. mean... Is it a beautiful poker hand? An unimaginable amount of money? Toilet thing? Come to GIT Harold night to find out!*
      </p>
      <p>
        *We cannot guarantee closure on this. 
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/flushprov

  - name: Raintown
    icon: fa-cloud-rain
    description: |
      <p>
          GIT House team at Glasgow Harold Night
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/raintownimprov


former-teams:

  - name: Family Dinner
    icon: fa-utensils
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2023/2024)
      </p>
      <p>
          Welcome to Family Dinner: Serving up some seriously funny improv and good clean fun that the whole family can enjoy
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/familydinner_improv

  - name: Ghost Fish
    icon: fa-ghost
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2023/2024)
      </p>
      <p>
          One of the all-time great improv groups - hugely influential in the sea, and the standard-bearers for how good, funny and artful long-form improv could be. At their best, they could play manic silliness and slow, patient moments in the same show. They're all dead humans who are now human-looking ghost fish.
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/ghostfishimprov

  - name: One Big Jacket
    icon: fa-tshirt
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2022/2023)
      </p>
      <p>
          One Big Jacket are warm, versatile and entirely waterproof. Made from several sustainably sourced improvisers and held together by the Harold structure.
          <br />** Must not be washed above 40°C
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/onebigjacket.improv

  - name: God's Lettuce
    icon: fa-leaf
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2022/2023)
      </p>
      <p>
          With members from Glasgow to Edinburgh, and even Falkirk, God’s Lettuce provides a diverse range of funny. Cool cats coming at ya large, as the Lettuce intended.
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/gods.lettuce.improv
        
  - name: President Dog
    icon: fa-dog
    description: |
      <p>
          GIT House team at Glasgow Harold Night (2022/2023)
      </p>
      <p>
          President Dog have a legally elected mandate to make you laugh
      </p>
    socials: 
      - title: instagram
        url: http://instagram.com/presidentdogimprov

events:
  - event-name: "An Improv Show (Glasgow Improv Theatre House Teams) Glasgow Comedy Fest"
    event-date: "2025-03-18"
    event-time: "18:30"
    event-url: "https://www.glasgowcomedyfestival.com/performances/an-improv-show-glasgow-improv-theatre-house-teams/"
    event-image: "https://www.glasgowcomedyfestival.com/wp-content/uploads/2024/11/11-20-2024-104835-8907.jpg"
    is-sold-out: false
    event-summary: "Two house teams from the Glasgow Improv Theatre create a comedy sketch show based on your suggestions!"
    venue-name: "Glasgow Improv Theatre"
    venue-address: "12 Renfield Street, Glasgow, G2 5AR"

  - event-name: "Pretty Thistle (An Improv Show) Glasgow Comedy Fest"
    event-date: "2025-03-18"
    event-time: "20:00"
    event-url: "https://www.glasgowcomedyfestival.com/performances/pretty-thistle-an-improv-show-glasgow-improv-theatre/"
    event-image: "https://www.glasgowcomedyfestival.com/wp-content/uploads/2024/11/11-18-2024-114510-4413.jpg"
    is-sold-out: false
    event-summary: "Pretty Thistle is an improv show from Martin James and John McInnes from the Glasgow Improv Theatre."
    venue-name: "Glasgow Improv Theatre"
    venue-address: "12 Renfield Street, Glasgow, G2 5AR"

  - event-name: "Jeff Khan: Christmas Day, Four AM (Glasgow Comedy Fest)"
    event-date: "2025-03-18"
    event-time: "21:30"
    event-url: "https://www.glasgowcomedyfestival.com/performances/jeff-khan-christmas-day-four-am-glasgow-improv-theatre/"
    event-image: "https://www.glasgowcomedyfestival.com/wp-content/uploads/2024/11/11-18-2024-105459-7345.jpg"
    is-sold-out: false
    event-summary: "An absurd hour of clowning from the Glasgow Improv Theatre’s Jeff Khan."
    venue-name: "Glasgow Improv Theatre"
    venue-address: "12 Renfield Street, Glasgow, G2 5AR"

  - event-name: "Couch Surfs the Web (Glasgow Comedy Fest)"
    event-date: "2025-03-25"
    event-time: "19:00"
    event-url: "https://www.glasgowcomedyfestival.com/performances/couch-surfs-the-web-glasgow-improv-theatre/"
    event-image: "https://www.glasgowcomedyfestival.com/wp-content/uploads/2024/11/11-18-2024-120957-9404.jpg"
    is-sold-out: false
    event-summary: "A night of improv comedy where Couch… SURFS THE WEB!"
    venue-name: "Glasgow Improv Theatre"
    venue-address: "12 Renfield Street, Glasgow, G2 5AR"

  - event-name: "Improv Cage Match (Glasgow Comedy Fest)"
    event-date: "2025-03-25"
    event-time: "20:30"
    event-url: "https://www.glasgowcomedyfestival.com/performances/improv-cage-match-glasgow-improv-theatre/"
    event-image: "https://www.glasgowcomedyfestival.com/wp-content/uploads/2024/11/11-18-2024-121121-5393.jpg"
    is-sold-out: false
    event-summary: "Two improv teams battle to be crowned champions of the Glasgow Improv Theatre this month. You decide who wins!"
    venue-name: "Glasgow Improv Theatre"
    venue-address: "12 Renfield Street, Glasgow, G2 5AR"
